param(
  [string[]]$Widgets,
  [string]$Port = '',
  [string]$BuildDirectory = '',
  [string]$ArduinoCli = '',
  [string]$ConfigFile = ''
)
$ErrorActionPreference = 'Stop'
$root = Split-Path $PSScriptRoot -Parent
$sketch = Join-Path $root 'firmware/WidgetDeck'
$choices = @('flight', 'gas', 'earthquake', 'wildfire', 'printer', 'space')

if ($PSBoundParameters.ContainsKey('Widgets')) {
  $selected = @($Widgets | ForEach-Object { $_.Split(',') } | ForEach-Object { $_.Trim().ToLowerInvariant() } | Where-Object { $_ })
  if (!$selected.Count) { throw 'Select at least one widget.' }
  foreach ($item in $selected) {
    if ($item -notin $choices) { throw "Unknown widget '$item'. Choose from: $($choices -join ', ')." }
  }
  $lines = @('#pragma once', '// Generated by tools/build.ps1. Local selection; do not commit.')
  foreach ($item in $choices) {
    $flag = if ($item -in $selected) { 1 } else { 0 }
    $lines += "#define DECK_ENABLE_$($item.ToUpperInvariant()) $flag"
  }
  Set-Content -LiteralPath (Join-Path $sketch 'src/widgets/widget_selection.h') -Value $lines -Encoding utf8
}

if (!$ArduinoCli) {
  $localCli = Join-Path $root '.cache/arduino-cli/arduino-cli.exe'
  if (Test-Path -LiteralPath $localCli) { $ArduinoCli = $localCli }
  else {
    $found = Get-Command arduino-cli -ErrorAction SilentlyContinue
    if (!$found) { throw 'Arduino CLI was not found. Install it and add arduino-cli to PATH, or pass -ArduinoCli.' }
    $ArduinoCli = $found.Source
  }
}
$config = if ($ConfigFile) { $ConfigFile } else { Join-Path $root '.cache/arduino-cli.yaml' }
$configArgs = @()
if (Test-Path -LiteralPath $config) { $configArgs = @('--config-file', $config) }
$board = 'esp32:esp32:esp32s3:USBMode=hwcdc,CDCOnBoot=cdc,FlashSize=16M,PartitionScheme=app3M_fat9M_16MB,PSRAM=opi'
if (!$BuildDirectory) { $BuildDirectory = Join-Path $root ('build/deck-' + (Get-Date -Format 'yyyyMMdd-HHmmss')) }
New-Item -ItemType Directory -Force -Path $BuildDirectory | Out-Null
& $ArduinoCli compile @configArgs --fqbn $board --build-path $BuildDirectory $sketch
if ($LASTEXITCODE -ne 0) { throw 'Firmware compilation failed.' }
Write-Output "Firmware output: $BuildDirectory"
if ($Port) {
  & $ArduinoCli upload @configArgs --fqbn $board --port $Port --input-dir $BuildDirectory $sketch
  if ($LASTEXITCODE -ne 0) { throw 'Firmware upload failed.' }
}
