// Regenerate compact, antialiased 40px logo masks from the attributed SVG originals.
// Usage: node tools/make_airline_logos.cjs [absolute/path/to/sharp]
const fs = require('fs');
const path = require('path');
const sharp = require(process.argv[2] || 'sharp');
const root = path.resolve(__dirname, '..');
const source = path.join(root, 'assets/airlines');
const manifest = JSON.parse(fs.readFileSync(path.join(source, 'manifest.json')));
(async () => {
  let output = '// Generated by tools/make_airline_logos.cjs; sources in assets/airlines/manifest.json.\n#pragma once\n#include <stdint.h>\nnamespace sky {\n';
  let totalBytes = 0;
  for (const entry of manifest.icons) {
    // Trim whitespace, retain aspect ratio and supersample before packing alpha.
    let svg = fs.readFileSync(path.join(source, entry.slug + '.svg'), 'utf8');
    // Use the intact Delta symbol, avoiding a tiny full wordmark. Keep the original SVG.
    if (entry.slug === 'delta') svg = svg.replace('viewBox="0 0 24 24"', 'viewBox="0 10.05 4.63 3.85"');
    entry.width = ['jetblue', 'fedex'].includes(entry.slug) ? 56 : 40;
    const { data, info } = await sharp(Buffer.from(svg), { density: 768 })
      .trim().resize(entry.width - 2, 38, { fit: 'contain', background: '#00000000' })
      .extend({ top: 1, bottom: 1, left: 1, right: 1, background: '#00000000' })
      .ensureAlpha().raw().toBuffer({ resolveWithObject: true });
    if (info.width !== entry.width || info.height !== 40 || info.channels !== 4) throw Error('Unexpected logo size');
    const packed = [];
    for (let i = 0; i < entry.width * 40; i += 2) {
      packed.push((Math.round(data[i * 4 + 3] / 17) << 4) | Math.round(data[(i + 1) * 4 + 3] / 17));
    }
    output += 'static const uint8_t logo' + entry.code + '[] = {\n';
    for (let i = 0; i < packed.length; i += 24) output += '  ' + packed.slice(i, i + 24).join(',') + ',\n';
    output += '};\n';
    totalBytes += packed.length;
  }
  output += 'struct Airline {const char *code, *name; const uint8_t *mask; uint8_t width;};\nstatic const Airline Airlines[] = {\n';
  for (const entry of manifest.icons) output += `  {"${entry.code}","${entry.title}",logo${entry.code},${entry.width}},\n`;
  output += '};\n}\n';
  fs.writeFileSync(path.join(root, 'firmware/WidgetDeck/src/widgets/flight/sky_airlines.h'), output);
  console.log(`Generated ${manifest.icons.length} logos: ${totalBytes} bytes of flash masks.`);
})().catch(error => { console.error(error); process.exitCode = 1; });
